Develop
grace-mugoiri/html-forms pull request #1
Opened 2019-03-26 15:30 UTC by grace-mugoiri

Great day to work with forms.

2019-03-26 17:28 UTC, nidalaa commented
Please follow the instructions about stickler configuration from here https://github.com/microverseinc/linters-config/tree/master/css.

2019-03-26 17:55 UTC, JamesOkunlade commented on index.html
> +    <title></title>
The title should not be left empty.

2019-03-26 17:57 UTC, JamesOkunlade commented on index.html
> +                <input>
Specify type and name attributes for all input elements.

2019-03-26 18:11 UTC, JamesOkunlade commented on index.html
> +                <p> <i> By clicking Create Account, you agree to our</p>
The tag <i> does not have a corresponding </i>.

2019-03-26 18:13 UTC, JamesOkunlade commented on index.html
> +                <p>our <a href="#">Privacy Statement</a></i></p>
Element "p" not allowed as child of the element "i" in this context. (Suppressing further errors from this subtree.)

2019-03-26 18:20 UTC, JamesOkunlade requested changes
Hello guys! Good work on the html-forms project. However, there are some changes you need to make as described in the comments.

You should always run your code through the W3C markup validator before requesting for code review to ensure your markups are without errors.

Effect the changes and send me another code review request.

2019-03-27 10:02 UTC, grace-mugoiri commented
we have made the requested changes.

2019-03-27 17:21 UTC, JamesOkunlade requested changes
I viewed your form in a browser and realised it doesn't look much like the mint sign up form.

1. The logo three icons on the form should be grabbed from the mint sign up page and added to your form.

2. Also, the sign in button and text at the top right corner of the page should be created in the project as well.

Please correct these changes and submit for another code review. 

Happy coding! :sunglasses:

2019-03-29 09:37 UTC, grace-mugoiri commented
-Fixed the form from scratch using CSS and HTML only. 
-Stickler still wont pass the review.

2019-03-29 16:58 UTC, JamesOkunlade approved these changes
### Looks perfect!! :sunglasses:
Merge the develop to master, close the PR and submit completion form. 

Regarding the stickler setup, there should be someone in your standup that has done it right. Ask for help from your team or bring it up in the full-time-students slack channel.

Good luck in your future projects. :+1::+1:

2019-03-31 13:53 UTC, merged